PerfectCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from app02.views import test

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/', include('crm.urls')),
    url(r'^kingadmin/', include('king_admin.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^teacher/', include('teacher.urls')),
]

crm/urls.py
from django.conf.urls import url,include
from crm import views

urlpatterns = [
    url(r'^$', views.dashboard,name='crm_home'),
    url(r'^login/$', views.user_login, name='crm_login'),
    url(r'^register/$', views.user_register, name='crm_register'),
    url(r'^logout/$', views.user_logout, name='crm_logout'),

    url(r'^enroll/$', views.add_student, name='add_student'),  # 第一步：报名信息录入
    url(r'^enroll/(\d+)/$', views.student_enroll, name='student_enroll'),  # 第二步：学生完善信息

    url(r'^audit_list/$', views.audit_list, name='audit_list'),  # 第三步：销售审核列表页
    url(r'^audit_list/(\d+)/$', views.audit, name='audit'),  # 第四步：销售审核学员

    url(r'^get_classes/(\d+)/$', views.get_classes, name='get_classes'), # 获取对应校区的所有班级

    url(r'^enroll/(\d+)/file_upload/$', views.enroll_file_upload, name='enroll_file_upload'),
    url(r'^enroll/file_delete/(\d+)/([\w|\.]+)/$', views.enroll_file_delete, name='enroll_file_delete'),
]

teacher/urls.py
from django.conf.urls import url
from teacher import views

urlpatterns = [
    url(r'^my_classes/$', views.class_list, name='class_list'),
    # 班级列表

    url(r'^my_classes/(\d+)/$', views.student_list, name='student_list'),
    # 班级学生列表

    url(r'^my_classes/homework_list/(\d+)/$', views.homework_list, name='homework_list'),
    # 查看学生的所有作业记录（包含未提交作业）

    url(r'^my_classes/homework_comment/(\d+)/$', views.homework_comment, name='homework_comment'),
    # 显示学生的所有作业记录（包含未提交作业）

    url(r'^review_homework_list/$', views.review_homeworks, name='review_homework_list'),
    # 显示学生的待批改作业
]

crm/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class UserProfile(AbstractUser):
    """用户信息"""
    # 一个角色可以对应多个用户，一个用户可以有多个角色
    role = models.ManyToManyField('Role', blank=True, null=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        db_table = '用户信息'


class Role(models.Model):
    """角色,可以包括学生，讲师等"""
    title = models.CharField(max_length=64, unique=True)
    menu = models.ManyToManyField('Menu')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '角色'
        verbose_name_plural = verbose_name
        db_table = '角色'


class CustomerInfo(models.Model):
    """客户信息表"""
    name = models.CharField(max_length=64, default=None, verbose_name='姓名')
    gender = models.IntegerField(choices=((0, '男'), (1, '女')), null=True, blank=True, verbose_name='性别')
    age = models.IntegerField(blank=True, null=True, verbose_name='年龄')
    id_num = models.CharField(max_length=32, blank=True, null=True, verbose_name='身份证号码')
    contact_type_choices = ((0, 'QQ'), (1, '微信'), (2, '手机'))
    contact_type = models.IntegerField(choices=contact_type_choices, default=0, verbose_name='联系方式')
    contact_info = models.CharField(max_length=64, unique=True, verbose_name='联系电话')
    emergency_contact = models.CharField(max_length=20, null=True, blank=True, verbose_name='紧急电话')
    consult_course = models.ManyToManyField('Course', verbose_name='咨询课程')
    consult_content = models.TextField(verbose_name='咨询大致内容')
    consultant = models.ForeignKey('UserProfile', verbose_name='课程顾问')
    status_choice = ((0, '未报名'), (1, '已报名'), (2, '已退学'))
    status = models.SmallIntegerField(choices=status_choice, default=0, verbose_name='状态')
    source_choices = ((0, 'QQ群'), (1, '51CTO'), (2, '知乎'), (3, '转介绍'), (4, '百度推广'), (5, '其他'))
    source = models.SmallIntegerField(choices=source_choices, verbose_name='来源')
    referral_from = models.ForeignKey('self', blank=True, null=True, verbose_name='转介绍人')
    date = models.DateField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '客户信息'
        verbose_name_plural = verbose_name
        db_table = '客户信息'


class CustomerFollowUp(models.Model):
    """客户跟踪记录表"""
    customer = models.ForeignKey('CustomerInfo')
    content = models.TextField(verbose_name='跟踪内容')
    user = models.ForeignKey('UserProfile', verbose_name='跟踪人')
    status_choice = ((0, '近期无报名计划'), (1, '2周内报名'), (2, '一个月内报名'), (3, '已报名'))
    status = models.SmallIntegerField(choices=status_choice)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.customer.name

    class Meta:
        verbose_name = '客户跟踪记录'
        verbose_name_plural = verbose_name
        db_table = '客户跟踪记录'


class Course(models.Model):
    """课程"""
    name = models.CharField(verbose_name='课程名称', max_length=64, unique=True)
    price = models.PositiveSmallIntegerField(verbose_name='价格')
    outline = models.TextField(verbose_name='大纲')
    period = models.SmallIntegerField(verbose_name="课程周期（月）")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name
        db_table = '课程'


class ClassList(models.Model):
    """班级列表"""
    branch = models.ForeignKey('Branch', verbose_name='校区')
    course = models.ForeignKey('Course')
    semester = models.SmallIntegerField(verbose_name='学期')
    teacher = models.ForeignKey('UserProfile',null=True,blank=True)
    start_date = models.DateField(verbose_name='开班日期', auto_now_add=True)
    contract_tempalte = models.ForeignKey('ContractTemplate', blank=True, null=True, verbose_name='关联合同模板')
    graduate_date = models.DateField(verbose_name='毕业日期', blank=True, null=True)
    class_type_choices = (
        (0, '脱产'),
        (1, '周末'),
        (2, '网络班'),
    )
    class_type = models.SmallIntegerField(choices=class_type_choices, default=0)

    def __str__(self):
        return "%s(%s)期" % (self.course.name, self.semester)

    class Meta:
        verbose_name = '班'
        verbose_name_plural = verbose_name
        db_table = '班'
        unique_together = ('course', 'semester', 'branch', 'class_type')


class CourseRecord(models.Model):
    """课程记录"""
    class_grade = models.ForeignKey('ClassList', verbose_name='上课班级')
    day_num = models.SmallIntegerField(verbose_name='课程节次')
    teacher = models.ForeignKey('UserProfile', verbose_name='讲师')
    title = models.CharField(verbose_name='本节主题', max_length=64)
    content = models.TextField(verbose_name='本节内容')
    has_homework = models.BooleanField(verbose_name='是否有作业', default=True)
    homework = models.TextField(verbose_name='作业需求', blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s第（%s）节" % (self.class_grade, self.day_num)

    class Meta:
        unique_together = ('day_num', 'class_grade')
        verbose_name = '课程记录'
        verbose_name_plural = verbose_name
        db_table = '课程记录'

class Branch(models.Model):
    """校区"""
    name = models.CharField(max_length=64, unique=True)
    address = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '校区'
        verbose_name_plural = verbose_name
        db_table = '校区'


class Menu(models.Model):
    """动态菜单"""
    name = models.CharField(max_length=64)
    url_type_choices = (
        (0, 'absolute'),
        (1, 'dynamic'),  # 带参数的url
    )
    url_type = models.SmallIntegerField(choices=url_type_choices)
    url_name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('name', 'url_name')
        db_table = '菜单'
        verbose_name = '菜单'
        verbose_name_plural = verbose_name


class ContractTemplate(models.Model):
    """合同"""
    name = models.CharField(max_length=32)
    content = models.TextField()
    create_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = '合同'


class StudentEnrollment(models.Model):
    """学员报名"""
    customer = models.ForeignKey('CustomerInfo')
    consultant = models.ForeignKey('UserProfile')
    class_grade = models.ForeignKey('ClassList')
    contract_agreed = models.BooleanField(default=False, verbose_name='同意条款')
    contract_signed_time = models.DateTimeField(blank=True, null=True, verbose_name='合同签订时间')
    contract_approved = models.BooleanField(default=False, verbose_name='审核通过')
    contract_approved_time = models.DateTimeField(blank=True, null=True, verbose_name='合同审核时间')

    def __str__(self):
        return '%s' % self.customer.name

    class Meta:
        unique_together = ['customer', 'class_grade']
        db_table = '学生报名'


class PaymentRecord(models.Model):
    """学员缴费记录"""
    enrollment = models.ForeignKey('StudentEnrollment')
    pay_amount = models.IntegerField(default=500)
    consultant = models.ForeignKey('CustomerInfo')
    payment_type_choices = ((0, '报名费'), (1, '学费'), (2, '退费'))
    payment_type = models.IntegerField(choices=payment_type_choices)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.enrollment

    class Meta:
        db_table = '缴费记录'


class Student(models.Model):
    """学生"""
    student = models.OneToOneField('StudentEnrollment')  #　只有走完报名流程才会成为正式学员
    user_account = models.OneToOneField('UserProfile')  # 创建用户

    class Meta:
        verbose_name = '学生'
        verbose_name_plural = verbose_name
        db_table = '学生'

    def __str__(self):
        return self.student.customer.name


class StudyRecord(models.Model):
    """学习记录表"""
    course_record = models.ForeignKey('CourseRecord')
    student = models.ForeignKey('Student')
    score_choices = (
        (100, 'A+'),
        (90, 'A'),
        (85, 'B+'),
        (80, 'B'),
        (75, 'B-'),
        (70, 'C+'),
        (60, 'C'),
        (40, 'C-'),
        (-50, 'D'),
        (0, 'N/A'),
        (-100, 'COPY'),
    )
    score = models.SmallIntegerField(choices=score_choices, default=0,
                                     verbose_name='成绩')

    show_choices = (
        (0, '缺勤'),
        (1, '已签到'),
        (0, '迟到'),
        (0, '早退'),
    )
    show_status = models.SmallIntegerField(choices=show_choices, default=1,
                                           verbose_name='考勤状态')
    note = models.TextField(verbose_name='成绩备注', blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s %s" % (self.course_record, self.student, self.score)

    class Meta:
        verbose_name = '学习记录'
        verbose_name_plural = verbose_name
        db_table = '学习记录'

teacher/models.py
from django.db import models

teacher/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError


class CommentForm(forms.Form):
    comment = forms.CharField(
        error_messages={
            'required':'评论不能为空',
        },
        widget=forms.Textarea(attrs={'class':'form-control','name':'comment'}),)

    score = forms.IntegerField(
        error_messages={
            'required': '分数不能为空',
            'invalid': '需要输入数字',
        },
        widget=widgets.TextInput(attrs={'class':'form-control','name':'score'})
    )

    def clean_score(self):
        value = self.cleaned_data['score']
        if int(value) not in list(range(101)):
            raise ValidationError('分数必须为在0-100中间')
        return value

teacher/views.py
from django.shortcuts import render,redirect
from crm import models
from django.contrib.auth.decorators import login_required
from student.models import HomeworkRecord,Homework
from .forms import CommentForm


@login_required
def class_list(request):
    class_list = models.ClassList.objects.all()
    return render(request,'teachers/class_list.html',locals())


@login_required
def student_list(request,class_id):
    class_grade = models.ClassList.objects.filter(id=class_id).first()
    enroll_student_list= class_grade.studentenrollment_set.all()
    return render(request,'teachers/student_list.html',locals())


from crm.models import Student

@login_required
def homework_list(request,stu_id):
    stu = Student.objects.filter(id=int(stu_id)).first()
    homework_lst = HomeworkRecord.objects.filter(student__id=int(stu_id))

    return render(request,'teachers/student_homework_list.html',locals())


@login_required
def review_homeworks(request):
    """待批改作业列表"""
    IS_TEACHER=False
    user = request.user
    for role in user.role.all():
        if role.title=='讲师':
            IS_TEACHER=True
    if IS_TEACHER:
        homework_lst = HomeworkRecord.objects.filter(student__student__class_grade__teacher=user,status=1)

    return render(request,'teachers/review_homework_list.html',locals())


@login_required
def homework_comment(request,record_id):
    form = CommentForm()
    homework_rec = HomeworkRecord.objects.filter(id=int(record_id)).first()
    stu_id = homework_rec.student.id

    if request.method=='POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            score = form.cleaned_data.get('score','')
            comment = form.cleaned_data.get('comment','')
            homework_rec = HomeworkRecord.objects.filter(id=int(record_id)).first()
            homework_rec.teacher_comments = comment
            homework_rec.score=int(score)
            homework_rec.status=2
            homework_rec.save()
            return redirect('/teacher/homework_list/%s/'% stu_id)

    return render(request, 'teachers/homework_coment.html',locals())

templates/teachers/class_list.html
{% extends 'base.html' %}

{% block title %}
<title>课程列表页</title>
{% endblock %}

{% block custom_css %}
    <style>
.navbar-header{
    width: 500px;
}
tbody{
    color: gray;
}
tbody a{
    color: gray;
}
.navbar-inverse .navbar-nav>li>a {
    color: #f8f8f8;
    font-size: 16px;
}
.navbar-inverse .navbar-brand {
    color: whitesmoke;
    font-size: 20px;
    font-weight: 500;
}
a:hover,a:link{
    text-decoration: none;
    cursor: pointer;
}
</style>
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
      <li><a href="{% url 'class_list' %}">班级列表</a></li>
    </ol>
{% endblock %}

{% block right_content %}
<div class="panel panel-primary">
<div class="panel-heading">
    <h4>班级列表</h4>
</div>
<div class="panel-body" style="">
    {#  导航栏 #}
    <div class="row">
        <table class="table table-striped">

            <tbody>
                {% for class_grade in class_list %}
                <tr>
                    <td><a href="{% url 'student_list' class_grade.id %}">{{ class_grade }}</a></td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
     </div><!--/row-->
</div>
</div>
{% endblock %}

templates/teachers/homework_coment.html
{% extends 'base.html' %}

{% block title %}
<title>作业批改</title>
{% endblock %}

{% block custom_css %}
<style>
.error_tip{
    color: red;
    font-size: 11px!important;
    margin-left: 20%;
}
</style>
{% endblock %}


{% block breadcrumb %}
    <ol class="breadcrumb">
      <li><a href="{% url 'class_list' %}">班级列表</a></li>
      <li><a href="{% url 'student_list' homework_rec.student.student.class_grade.id %}" class=""
      >{{ homework_rec.student.student.class_grade }}</a></li>
      <li><a href="{% url 'homework_list' homework_rec.student.id %}" class="">{{ homework_rec.student }}</a></li>
      <li><a href="{% url 'homework_comment' homework_rec.id %}" class="">{{ homework_rec.homework.title }}</a></li>
    </ol>
{% endblock %}


{% block right_content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3>作业打分及评语</h3>
        </div>

        <div class="panel-body" style="">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="score">作业</label>
                    <input type="text" disabled class="form-control" id="score" value="{{ homework_rec.homework.title }}">
                </div>

                <div class="form-group">
                    <label for="score">学生</label>
                    <input type="text" disabled class="form-control" id="score"
                           value="{{ homework_rec.student }}">
                </div>

                <div class="form-group">
                    <label for="score">分数</label><span class="error_tip">{{ form.errors.score.0 }}</span>
{#                    <input type="text" class="form-control" id="score" placeholder="分数" name="score">#}
                    {{ form.score }}
                </div>

                 <label for="exampleInputEmail1">评语</label><span class="error_tip">{{ form.errors.comment.0 }}</span>
{#                <textarea class="form-control" rows="5" name="comment"></textarea>#}
                    {{ form.comment }}

                <input type="submit" class="btn btn-success btn-block" value="提交" style="margin-top: 20px">
            </form>
        </div>
    </div>
{% endblock %}

templates/teachers/review_homework_list.html
{% extends 'base.html' %}

{% load student_tag %}

{% block title %}
<title>待批改作业页面</title>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="">待批改作业</a></li>
</ol>
{% endblock %}

{% block right_content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3>待批改作业</h3>
        </div>
        <div class="panel-body" style="">
             <table class="table-striped table">
                <thead>
                     <tr>
                        <td class="col-md-1">编号</td>
                        <td class="col-md-3">名称</td>
                        <td class="col-md-1">学生</td>
                        <td class="col-md-3">班级</td>
                        <td class="col-md-3">上传日期</td>
                        <td class="col-md-1">作业</td>
                    </tr>
                </thead>
                <tbody>
                    {% for homework_record in homework_lst %}
                    <tr>
                        <td><a href="{% url 'homework_comment' homework_record.id %}">{{ homework_record.id }}</a></td>
                        <td>{{ homework_record.homework.title }}</td>
                        <td>{{ homework_record.student }}</td>
                        <td>{{ homework_record.student.student.class_grade }}</td>
                        <td>{% to_string homework_record.upload_time %}</td>

                        <!-- 获取当前作业记录 学生上传的文件名称 -->
                        {% get_file_name homework_record.id as file_name %}
                        <!-- 根据之前获取的文件名称用于下载地址的参数-->
                        <td><a href="{% if file_name %}{% url 'homework_download' homework_record.id file_name %}{% else %}#{% endif %}">下载</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}

templates/teachers/student_homework_list.html
{% extends 'base.html' %}

{% load student_tag %}

{% block title %}
<title>学生作业记录</title>
{% endblock %}

{% block custom_css %}
<style>
.correct_status{
    color: red;
}
</style>
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
      <li><a href="{% url 'class_list' %}">班级列表</a></li>
      <li><a href="{% url 'student_list' stu.student.class_grade.id %}" class="">{{ stu.student.class_grade }}</a></li>
      <li><a href="{% url 'homework_list' stu_id %}" class="active">{{ stu }}</a></li>
    </ol>
{% endblock %}


{% block right_content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>学生作业记录</h4>
        </div>
        <div class="panel-body" style="">
             <table class="table-bordered table">
                <thead>
                     <tr>
                        <td class="col-md-1">编号</td>
                        <td class="col-md-2">名称</td>
                        <td class="col-md-1">学生</td>
                        <td class="col-md-2">班级</td>
                        <td class="col-md-2">上传日期</td>
                        <td class="col-md-1">批改状态</td>
                        <td class="col-md-1">分数</td>
                        <td class="col-md-1">作业</td>
                    </tr>
                </thead>

                <tbody>
                    {% for homework_record in homework_lst %}
                    <tr>
                        <td><a href="{% ifequal homework_record.status 2 %}#{% else %}{% url 'homework_comment' homework_record.id %}{% endifequal %}">{{ homework_record.id }}</a></td>
                        <td>{{ homework_record.homework.title }}</td>
                        <td>{{ homework_record.student }}</td>
                        <td>{{ homework_record.student.student.class_grade }}</td>
                        <td>{% to_string homework_record.upload_time %}</td>
                        <td class="{% ifequal homework_record.status 1 %}correct_status{% else %}{% url 'homework_comment' homework_record.id %}{% endifequal %}">{{ homework_record.get_status_display }}</td>
                        <td>{{ homework_record.score }}</td>
                        <!-- 获取当前作业记录 学生上传的文件名称 -->
                        {% get_file_name homework_record.id as file_name %}
                        <!-- 根据之前获取的文件名称用于下载地址的参数-->
                        <td><a href="{% if file_name %}{% url 'homework_download' homework_record.id file_name %}{% else %}#{% endif %}">下载</a></td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>

    </div>
{% endblock %}

templates/teachers/student_list.html
{% extends 'base.html' %}

{% block title %}
    <title>班级学生列表</title>
{% endblock %}


{% block breadcrumb %}
    <ol class="breadcrumb">
      <li><a href="{% url 'class_list' %}">班级列表</a></li>
      <li><a href="{% url 'student_list' class_id %}" class="active">{{ class_grade }}</a></li>
    </ol>
{% endblock %}

{% block right_content %}
    <div class="panel panel-primary">
    <div class="panel-heading">
        <h4>学生列表</h4>
    </div>
    <div class="panel-body" style="">
        {#  导航栏 #}
        <div class="row">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td class="col-lg-1">学号</td>
                        <td class="col-md-2">姓名</td>
                        <td class="col-md-2">性别</td>
                        <td class="col-md-2">年龄</td>
                    </tr>
                </thead>

                <tbody>
                    {% for stu_enroll in enroll_student_list %}
                    <tr>
                        <td><a href="{% url 'homework_list' stu_enroll.student.id %}">{{ stu_enroll.student.id }}</a></td>
                        <td>{{ stu_enroll.customer.name }}</td>
                        <td>{{ stu_enroll.customer.get_gender_display }}</td>
                        <td>{{ stu_enroll.customer.age }}</td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
         </div><!--/row-->
    </div>
</div>
{% endblock %}

templates/teachers/students_homework_uploads.html
{% extends 'student/homework_list.html' %}
{% load student_tag %}

{% block title %}
<title>待批改作业</title>
{% endblock %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3>学生作业记录</h3>
        </div>
        <div class="panel-body" style="">
            {#  导航栏 #}
            <div class="row">
                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td class="col-md-2">作业名称</td>
                        <td class="col-md-2">作业状态</td>
                        <td class="col-md-1">分数</td>
                        <td class="col-md-1">学生</td>
                        <td class="col-md-2 ">截止日期</td>
                        <td class="col-md-1">链接</td>
                    </tr>

                    {% for homework in homework_lst %}
                    <tr>
                        <td><a href="#">{{ homework.homework.title }}</a></td>
                        <td>{{ homework.get_status_display }}</td>
                        <td>{{ homework.score }}</td>
                        <td>{{ homework.student.customer.name }}</td>
                        <td>{% get_date homework.homework.publish_date homework.homework.suggested_complete_days %}</td>
                        <td><a href="{% url 'homework_download' homework.id 'file_name' %}">下载</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div><!--/row-->
        </div>
</div>
{% endblock %}